// The Supabase client is the single "adapter" to the outside world. All feature
// code imports THIS, never @supabase/supabase-js directly:
//
//   import { supabase } from "@/integrations/supabase/client";
//
// The per-portal storage-key logic lives in ./clientConfig so this file can be
// regenerated by the Supabase integration without losing the multi-app session
// isolation.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseStorageKey, purgeLegacySupabaseKey } from "./clientConfig";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase env vars. Copy .env.example to .env and set " +
      "VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.",
  );
}

purgeLegacySupabaseKey();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: getSupabaseStorageKey(),
    persistSession: true,
    autoRefreshToken: true,
  },
});
